### ISSUE TITLE
Ajouter logs côté serveur

### ISSUE THREAD

**Issue by SaphireVert** [ponsfrilus/ict-bot#14]
• Ajouter des logs de qui demande quoi à quelle heure (2019-11-25 HH-MM:SS username ou nom prénom)
• Supprimer le console.debug() de la commande /info

**Comment by ponsfrilus** [comment]
@SaphireVert Ce pourrait aussi être cool de logguer vers un fichier en plus de stdout (voir https://stackoverflow.com/a/21061306/960623)

**Comment by ponsfrilus** [comment]
Closed by https://github.com/ponsfrilus/ict-bot/pull/23
